import json
import os
import sys
import types
from pathlib import Path

import pytest
import yaml

from matraix import cli
from matraix.launch_env import (
    PERSONA_LANGUAGE_ENV,
    PERSONA_LANGUAGE_SOURCE_ENV,
    build_persona_language_env,
    required_pythonpath_entries,
)
from playground.persona_language import resolve_persona_language_with_source


def _write_job(
    tmp_path: Path,
    *,
    header_exports: list[str] | None = None,
    sidecar: dict | None = None,
) -> Path:
    jobs_dir = tmp_path / "configs" / "jobs" / "application-task-job-recipe"
    jobs_dir.mkdir(parents=True, exist_ok=True)
    config = jobs_dir / "example-survey-auto-n1.yaml"
    header = [
        "# Generated by application/scripts/generate_application_job.py",
        "# Run (after exporting API keys):",
        "#   export ANTHROPIC_API_KEY=...",
    ]
    header.extend(header_exports or [])
    header.append("#   uv run matraix run -c <this-file>")
    config.write_text(
        "\n".join(header) + "\njob_name: example\ntasks: []\n", encoding="utf-8"
    )
    if sidecar is not None:
        config.with_suffix(".meta.json").write_text(
            json.dumps(sidecar), encoding="utf-8"
        )
    return config


def test_header_exports_only_pick_up_matrix_vars(tmp_path: Path) -> None:
    config = _write_job(
        tmp_path,
        header_exports=["#   export MATRIX_SURVEY_TASK_PATH=application/tasks/foo"],
    )
    env = cli._task_env_from_header(config)
    assert env == {"MATRIX_SURVEY_TASK_PATH": "application/tasks/foo"}


def test_sidecar_derives_survey_and_chat_task_env(tmp_path: Path) -> None:
    survey = _write_job(
        tmp_path,
        sidecar={"task": "application/tasks/foo", "trial_profile": "json_survey"},
    )
    assert cli._task_env_from_sidecar(survey) == {
        "MATRIX_SURVEY_TASK_PATH": "application/tasks/foo"
    }
    chat = _write_job(
        tmp_path,
        sidecar={"task": "application/tasks/bar", "trial_profile": "user_sim_chat"},
    )
    assert cli._task_env_from_sidecar(chat) == {
        "MATRIX_CHATBOT_TASK_PATH": "application/tasks/bar"
    }


def test_resolve_run_invocation_builds_env_and_relative_config(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.delenv("MATRIX_SURVEY_TASK_PATH", raising=False)
    monkeypatch.delenv("PYTHONPATH", raising=False)
    config = _write_job(
        tmp_path,
        sidecar={"task": "application/tasks/foo", "trial_profile": "json_survey"},
    )
    argv, env_updates = cli.resolve_run_invocation(config, tmp_path, ["--yes"])
    assert argv == [
        "run",
        "-c",
        "configs/jobs/application-task-job-recipe/example-survey-auto-n1.yaml",
        "--yes",
    ]
    assert env_updates["MATRIX_SURVEY_TASK_PATH"] == "application/tasks/foo"
    assert env_updates["PYTHONPATH"].split(os.pathsep) == required_pythonpath_entries(
        tmp_path
    )


def test_resolve_run_invocation_respects_user_exported_env(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.setenv("MATRIX_SURVEY_TASK_PATH", "application/tasks/custom")
    config = _write_job(
        tmp_path,
        sidecar={"task": "application/tasks/foo", "trial_profile": "json_survey"},
    )
    _, env_updates = cli.resolve_run_invocation(config, tmp_path)
    assert "MATRIX_SURVEY_TASK_PATH" not in env_updates


def test_persona_language_env_normalizes_tokens_and_records_explicit_source() -> None:
    assert build_persona_language_env(" zh-cn ") == {
        PERSONA_LANGUAGE_ENV: "zh-Hans",
        PERSONA_LANGUAGE_SOURCE_ENV: "explicit",
    }


def test_persona_language_validation_rejects_unknown_tokens() -> None:
    with pytest.raises(ValueError, match="en, ko, zh-Hans, zh-Hant, ja, pt-BR, es"):
        build_persona_language_env("fr")


def test_resolve_run_invocation_explicit_language_overrides_env_and_generated_config(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.setenv(PERSONA_LANGUAGE_ENV, "en")
    monkeypatch.setenv(PERSONA_LANGUAGE_SOURCE_ENV, "env")
    config = _write_job(
        tmp_path,
        header_exports=[
            "#   export MATRIX_PERSONA_LANGUAGE=ko",
            "#   export MATRIX_PERSONA_LANGUAGE_SOURCE=task",
        ],
    )

    _, env_updates = cli.resolve_run_invocation(
        config, tmp_path, persona_language="ZH-hant"
    )

    assert env_updates[PERSONA_LANGUAGE_ENV] == "zh-Hant"
    assert env_updates[PERSONA_LANGUAGE_SOURCE_ENV] == "explicit"


def test_resolve_run_invocation_without_language_preserves_existing_env_behavior(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.setenv(PERSONA_LANGUAGE_ENV, "ko")
    monkeypatch.setenv(PERSONA_LANGUAGE_SOURCE_ENV, "env")
    config = _write_job(tmp_path)

    _, env_updates = cli.resolve_run_invocation(config, tmp_path)

    assert PERSONA_LANGUAGE_ENV not in env_updates
    assert PERSONA_LANGUAGE_SOURCE_ENV not in env_updates
    assert os.environ[PERSONA_LANGUAGE_ENV] == "ko"
    assert os.environ[PERSONA_LANGUAGE_SOURCE_ENV] == "env"


def test_main_run_delegates_to_harbor_with_launch_env(
    tmp_path: Path, monkeypatch
) -> None:
    root = tmp_path / "checkout"
    (root / "environment" / "runtime" / "harbor").mkdir(parents=True)
    (root / "pyproject.toml").write_text("[project]\nname='x'\n", encoding="utf-8")
    config = _write_job(
        root,
        sidecar={"task": "application/tasks/foo", "trial_profile": "json_survey"},
    )

    calls: dict[str, object] = {}

    def fake_app(*, args: list[str], prog_name: str) -> None:
        calls["args"] = args
        calls["prog_name"] = prog_name
        calls["cwd"] = Path.cwd()
        calls["survey_task"] = os.environ.get("MATRIX_SURVEY_TASK_PATH")
        calls["pythonpath"] = os.environ.get("PYTHONPATH", "")

    stub = types.ModuleType("harbor.cli.main")
    stub.app = fake_app
    monkeypatch.setitem(sys.modules, "harbor.cli.main", stub)
    monkeypatch.delenv("MATRIX_SURVEY_TASK_PATH", raising=False)
    monkeypatch.delenv("PYTHONPATH", raising=False)

    original_cwd = Path.cwd()
    original_sys_path = list(sys.path)
    try:
        cli.main(["run", "-c", str(config), "--yes"])
    finally:
        os.chdir(original_cwd)
        sys.path[:] = original_sys_path

    assert calls["args"] == [
        "run",
        "-c",
        "configs/jobs/application-task-job-recipe/example-survey-auto-n1.yaml",
        "--yes",
    ]
    assert calls["cwd"] == root.resolve()
    assert calls["survey_task"] == "application/tasks/foo"
    assert str(calls["pythonpath"]).split(os.pathsep)[0] == str(root.resolve())


def test_main_run_missing_config_exits_with_message(tmp_path: Path) -> None:
    with pytest.raises(SystemExit) as excinfo:
        cli.main(["run", "-c", str(tmp_path / "missing.yaml")])
    assert "not found" in str(excinfo.value)


def _fake_checkout(tmp_path: Path) -> Path:
    root = tmp_path / "checkout"
    (root / "environment" / "runtime" / "harbor").mkdir(parents=True)
    (root / "pyproject.toml").write_text("[project]\nname='x'\n", encoding="utf-8")
    return root


def _stub_harbor(monkeypatch) -> dict[str, object]:
    calls: dict[str, object] = {}

    def fake_app(*, args: list[str], prog_name: str) -> None:
        calls["args"] = args
        calls["pythonpath"] = os.environ.get("PYTHONPATH", "")
        calls["persona_language"] = os.environ.get(PERSONA_LANGUAGE_ENV)
        calls["persona_language_source"] = os.environ.get(
            PERSONA_LANGUAGE_SOURCE_ENV
        )

    stub = types.ModuleType("harbor.cli.main")
    stub.app = fake_app
    monkeypatch.setitem(sys.modules, "harbor.cli.main", stub)
    monkeypatch.delenv("PYTHONPATH", raising=False)
    return calls


def test_main_run_accepts_positional_config(tmp_path: Path, monkeypatch) -> None:
    root = _fake_checkout(tmp_path)
    config = _write_job(
        root,
        sidecar={"task": "application/tasks/foo", "trial_profile": "json_survey"},
    )
    calls = _stub_harbor(monkeypatch)
    monkeypatch.delenv("MATRIX_SURVEY_TASK_PATH", raising=False)

    original_cwd = Path.cwd()
    original_sys_path = list(sys.path)
    try:
        cli.main(["run", str(config), "--yes"])
    finally:
        os.chdir(original_cwd)
        sys.path[:] = original_sys_path

    assert calls["args"] == [
        "run",
        "-c",
        "configs/jobs/application-task-job-recipe/example-survey-auto-n1.yaml",
        "--yes",
    ]


def test_main_run_accepts_persona_language_override(tmp_path: Path, monkeypatch) -> None:
    root = _fake_checkout(tmp_path)
    config = _write_job(root)
    calls = _stub_harbor(monkeypatch)
    monkeypatch.delenv(PERSONA_LANGUAGE_ENV, raising=False)
    monkeypatch.delenv(PERSONA_LANGUAGE_SOURCE_ENV, raising=False)

    original_cwd = Path.cwd()
    original_sys_path = list(sys.path)
    try:
        cli.main(
            [
                "run",
                "-c",
                str(config),
                "--persona-language",
                "ZH-hant",
                "--yes",
            ]
        )
    finally:
        os.chdir(original_cwd)
        sys.path[:] = original_sys_path
        monkeypatch.delenv(PERSONA_LANGUAGE_ENV, raising=False)
        monkeypatch.delenv(PERSONA_LANGUAGE_SOURCE_ENV, raising=False)

    assert calls["args"] == [
        "run",
        "-c",
        str(
            Path("configs")
            / "jobs"
            / "application-task-job-recipe"
            / "example-survey-auto-n1.yaml"
        ),
        "--yes",
    ]
    assert calls["persona_language"] == "zh-Hant"
    assert calls["persona_language_source"] == "explicit"


def test_cli_language_override_beats_generated_agent_kwargs(
    tmp_path: Path, monkeypatch
) -> None:
    root = _fake_checkout(tmp_path)
    config = _write_job(root)
    config.write_text(
        """job_name: example
agents:
- name: persona-json-survey
  kwargs:
    persona_language: en
    persona_language_source: follow_ui
tasks: []
""",
        encoding="utf-8",
    )
    calls: dict[str, object] = {}

    def fake_app(*, args: list[str], prog_name: str) -> None:
        config_arg = Path(args[args.index("-c") + 1])
        payload = yaml.safe_load(config_arg.read_text(encoding="utf-8"))
        kwargs = payload["agents"][0]["kwargs"]
        resolution = resolve_persona_language_with_source(
            kwargs["persona_language"],
            requested_source=kwargs["persona_language_source"],
        )
        calls["language"] = resolution.language
        calls["source"] = resolution.source

    stub = types.ModuleType("harbor.cli.main")
    stub.app = fake_app
    monkeypatch.setitem(sys.modules, "harbor.cli.main", stub)
    monkeypatch.delenv(PERSONA_LANGUAGE_ENV, raising=False)
    monkeypatch.delenv("MATRIX_PERSONA_LANGUAGE_OVERRIDE", raising=False)
    monkeypatch.delenv(PERSONA_LANGUAGE_SOURCE_ENV, raising=False)

    original_cwd = Path.cwd()
    original_sys_path = list(sys.path)
    try:
        cli.main(
            [
                "run",
                "-c",
                str(config),
                "--persona-language",
                "zh-Hant",
            ]
        )
    finally:
        os.chdir(original_cwd)
        sys.path[:] = original_sys_path
        monkeypatch.delenv(PERSONA_LANGUAGE_ENV, raising=False)
        monkeypatch.delenv("MATRIX_PERSONA_LANGUAGE_OVERRIDE", raising=False)
        monkeypatch.delenv(PERSONA_LANGUAGE_SOURCE_ENV, raising=False)

    assert calls == {"language": "zh-Hant", "source": "explicit"}


def test_main_rejects_unknown_persona_language(tmp_path: Path) -> None:
    with pytest.raises(SystemExit) as excinfo:
        cli.main(
            [
                "run",
                "--repo-root",
                str(tmp_path),
                "--persona-language",
                "fr",
            ]
        )
    assert excinfo.value.code == 2


def test_main_run_without_config_passes_args_through(
    tmp_path: Path, monkeypatch
) -> None:
    root = _fake_checkout(tmp_path)
    calls = _stub_harbor(monkeypatch)
    monkeypatch.chdir(root)

    original_sys_path = list(sys.path)
    try:
        cli.main(["run", "-p", "application/tasks/foo", "-a", "oracle"])
    finally:
        sys.path[:] = original_sys_path

    assert calls["args"] == ["run", "-p", "application/tasks/foo", "-a", "oracle"]
    assert str(calls["pythonpath"]).split(os.pathsep)[0] == str(root.resolve())


def test_main_run_sets_max_cost_usd_env(tmp_path: Path, monkeypatch) -> None:
    root = _fake_checkout(tmp_path)
    config = _write_job(
        root,
        sidecar={"task": "application/tasks/foo", "trial_profile": "json_survey"},
    )
    calls = _stub_harbor(monkeypatch)
    monkeypatch.delenv("MATRIX_MAX_COST_USD", raising=False)
    monkeypatch.delenv("MATRIX_SURVEY_TASK_PATH", raising=False)

    original_cwd = Path.cwd()
    original_sys_path = list(sys.path)
    try:
        cli.main(["run", "-c", str(config), "--max-cost-usd", "1.25", "--yes"])
    finally:
        os.chdir(original_cwd)
        sys.path[:] = original_sys_path

    assert os.environ.get("MATRIX_MAX_COST_USD") == "1.25"
    assert calls["args"] == [
        "run",
        "-c",
        "configs/jobs/application-task-job-recipe/example-survey-auto-n1.yaml",
        "--yes",
    ]


def test_main_results_prints_text_summary(tmp_path: Path, monkeypatch, capsys) -> None:
    from matraix.job_results import collect_job_results

    job = tmp_path / "jobs" / "cli-results-demo"
    trial = job / "trial-1"
    output = trial / "artifacts" / "app" / "output"
    output.mkdir(parents=True)
    (job / "result.json").write_text(
        json.dumps({"stats": {"n_completed_trials": 1, "n_errored_trials": 0}}),
        encoding="utf-8",
    )
    (trial / "result.json").write_text(
        json.dumps({"verifier_result": {"rewards": {"reward": 1.0}}}),
        encoding="utf-8",
    )
    (output / "survey_result.json").write_text(
        json.dumps({"answers": [{"questionId": "q0", "value": "yes"}]}),
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)
    cli.main(["results", "cli-results-demo", "--repo-root", str(tmp_path)])
    out = capsys.readouterr().out
    assert "cli-results-demo" in out
    assert "q0" in out
    report = collect_job_results(job)
    assert report.question_distributions["q0"]["yes"] == 1
